[package]
name = "hebbot"
version = "2.1.0"
authors = ["Felix Häcker <haeckerfelix@gnome.org>"]
edition = "2018"

[dependencies]
matrix-sdk = { git="https://github.com/a-kenji/matrix-rust-sdk", branch = "break-encryption" }
serde = "1.0"
serde_json = "1.0"
url = "2.2"
tokio = { version="1.7", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.4"
chrono = { version = "0.4", features = ["serde"] }
regex = "1.5"
rand = "0.8"
mime = "0.3"
toml = "0.5"
async-process = "1.2"
